version: "4.19.0"

services:
  db:
      image: postgres
      restart: "no"
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        POSTGRES_IP: localhost
        POSTGRES_PORT: 5432
      ports:
        - "5432:5432"
  mongo:
    image: mongo
    restart: "no"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGI_INITDB_DATABASE: madn
  persistence:
    image: madn-persistence-service
    build:
      context: ./services/persistence/
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    stdin_open: true
    container_name: persistence_service
    environment:
      FILEIO_SERVICE_HOST: persistence
      FILEIO_SERVICE_PORT: 8080
      DOCKER : "true"
    tty: true
  tools:
    image: madn-tools-service
    build:
      context: ./services/tools/
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    stdin_open: true
    container_name: tools_service
    environment:
      FILEIO_SERVICE_HOST: tools
      FILEIO_SERVICE_PORT: 8081
    tty: true

  main:
    image: madn-service
    build:
      context: ./services/main
      dockerfile: ./Dockerfile
    stdin_open: true
    container_name: madn_service
    depends_on:
      - persistence
      - tools
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: $DISPLAY
      CONNECTFOUR_SERVICE_HOST: connectfour
      CONNECTFOUR_SERVICE_PORT: 8080
      FILEIO_SERVICE_HOST: persistence
      FILEIO_SERVICE_PORT: 8081
      DOCKER : "true"

 