version: "4.19.0"

services:
  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        POSTGRES_IP: localhost
        POSTGRES_PORT: 5432
      ports:
        - "5432:5432"
 # persistence:
 #   image: madn-persistence-service
 #   #build:
 #   #  context: ./persistence/
 #   #  dockerfile: ./Dockerfile
 #   ports:
 #     - "8080:8080"
 #   stdin_open: true
 #   container_name: persistence_service
 #   environment:
 #     FILEIO_SERVICE_HOST: persistence
 #     FILEIO_SERVICE_PORT: 8080
 #   tty: true
 # tools:
 #   image: madn-tools-service
 #   #build:
 #   #  context: ./tools/
 #   #  dockerfile: ./Dockerfile
 #   ports:
 #     - "8081:8081"
 #   stdin_open: true
 #   container_name: tools_service
 #   environment:
 #     FILEIO_SERVICE_HOST: tools
 #     FILEIO_SERVICE_PORT: 8081
 #   tty: true
#
 # main:
 #   image: madn-service
 #   #build:
 #   #  context: ./src
 #   #  dockerfile: ./Dockerfile
 #   stdin_open: true
 #   container_name: madn_service
 #   depends_on:
 #     - persistence
 #     - tools
 #   volumes:
 #     - /tmp/.X11-unix:/tmp/.X11-unix
 #   environment:
 #     DISPLAY: $DISPLAY
 #     CONNECTFOUR_SERVICE_HOST: connectfour
 #     CONNECTFOUR_SERVICE_PORT: 8080
 #     FILEIO_SERVICE_HOST: persistence
 #     FILEIO_SERVICE_PORT: 8081
#