
Skip to content
Pull requests
Issues
Marketplace
Explore
@Manz2
NiclasEgeler /
SE
Public

Code
Issues
Pull requests
Actions
Projects 1
Wiki
Security

    Insights

SE/.github/workflows/scala.yml
@NiclasEgeler
NiclasEgeler Create scala.yml
Latest commit 8a11ecf on 17 Nov 2021
History
1 contributor
22 lines (18 sloc) 349 Bytes
name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test

    © 2022 GitHub, Inc.

    Terms
    Privacy
    Security
    Status
    Docs
    Contact GitHub
    Pricing
    API
    Training
    Blog
    About

Loading complete